[package]
name = "hbbft"
version = "0.1.0"
authors = ["Vladimir Komendantskiy <komendantsky@gmail.com>"]

[dependencies]
bincode = "1.0.0"
env_logger = "0.5.10"
itertools = "0.7"
log = "0.4.1"
merkle = { git = "https://github.com/afck/merkle.rs", branch = "public-proof" }
protobuf = { version = "1.6.0", optional = true }
rand = "0.4.2"
reed-solomon-erasure = "3.0"
ring = "^0.12"
serde = "1.0.55"
serde_derive = { version = "1.0.55", optional = true }

[features]
serialization-protobuf = [ "protobuf", "protobuf-codegen-pure" ]
serialization-serde = [ "merkle/serialization-serde", "serde_derive" ]

[build-dependencies]
protobuf-codegen-pure = { version = "1.6.0", optional = true }

[dev-dependencies]
colored = "1.6"
crossbeam = "0.3.2"
crossbeam-channel = "0.1"
docopt = "0.8"
serde_derive = "1.0.55"

[[example]]
name = "consensus-node"
required-features = [ "serialization-protobuf" ]

[[example]]
name = "simulation"
